modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/cakeGit/Pattern-Schematics-Multiloader/issues"
license = "MIT"

[[mods]]
modId = "create_pattern_schematics"
version = "${version}"
displayName = "Create: Pattern Schematics"
authors = "Cak"
description = '''
Adds repeating pattern based schematics to create!
'''
logoFile = "logo.png"

[[dependencies.create_pattern_schematics]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_pattern_schematics]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_pattern_schematics]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"