modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/cakeGit/Pattern-Schematics-Multiloader/issues"
license = "MIT"

[[mods]]
modId = "create_pattern_schematics"
version = "${mod_version}"
displayName = "Create: Pattern Schematics"
authors = "Cake"
description = '''
Adds repeating pattern based schematics to create!
'''
logoFile = "logo.png"
displayURL = "https://modrinth.com/mod/create-pattern-schematics"
updateJSONURL = "https://raw.githubusercontent.com/cakeGit/Pattern-Schematics-Multiloader/1.20.1/forge-updates.json"

[[dependencies.create_pattern_schematics]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="${forge_version_range}" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.create_pattern_schematics]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_pattern_schematics]]
modId="create"
mandatory=true
versionRange="[6.0.8,6.1.0)"
ordering="NONE"
side="BOTH"
# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
